version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-app
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - fastapi-network


  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    env_file: .env
    networks:
      - fastapi-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    env_file: .env
    restart: always
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge

