version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-app
    env_file:
      - .env  # .env faylini konteynerda ishlatish
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    networks:
      - fastapi-network


  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    env_file: .env
    networks:
      - fastapi-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    env_file: .env
    restart: always
    networks:
      - fastapi-network


  postgres_db:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
